/*
 * Copyright 2026 AzoraTech
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.azora.lang.backend

import org.azora.lang.ir.IrBinaryOp
import org.azora.lang.ir.IrExpr
import org.azora.lang.ir.IrFunction
import org.azora.lang.ir.IrProgram
import org.azora.lang.ir.IrStmt
import org.azora.lang.ir.IrTopLevel
import org.azora.lang.ir.IrType
import org.azora.lang.ir.IrUnaryOp
import kotlin.text.iterator

/**
 * Backend — lowers [IrProgram] to LLVM IR text (`.ll` format).
 *
 * Type mapping:
 *   Int    → i32
 *   Real   → double
 *   Bool   → i1
 *   String → i8* (pointer to null-terminated C string)
 *   Unit   → void
 *
 * Strings are emitted as global constants. `println` is declared as an
 * external call to `puts` (for strings) or `printf` (for formatted output).
 */
class LlvmCodegen {

    private val out = StringBuilder()
    private var tmpCounter = 0
    private var labelCounter = 0
    private var stringCounter = 0
    private val stringConstants = mutableListOf<Pair<String, String>>() // @name -> value
    private val localVars = mutableMapOf<String, String>() // var name -> LLVM register/alloca
    private var usesPuts = false
    private var usesPrintf = false
    private var usesAbort = false

    /**
     * Generates LLVM IR text (`.ll` format) from the given IR program.
     *
     * The output includes external declarations for `puts` and `printf`,
     * function definitions, and string constant globals.
     *
     * @param program the optimized IR program to lower to LLVM IR
     * @return the generated LLVM IR text as a string
     */
    fun generate(program: IrProgram): String {
        out.clear()
        tmpCounter = 0
        labelCounter = 0
        stringCounter = 0
        stringConstants.clear()
        usesPuts = false
        usesPrintf = false
        usesAbort = false

        // Generate body into a separate buffer (so we know which externals are used)
        val body = StringBuilder()
        val savedOut = out
        // Temporarily redirect output to body buffer
        val bodyBuilder = StringBuilder()

        // Emit globals
        val globals = program.items.filterIsInstance<IrTopLevel.Global>()
        if (globals.isNotEmpty()) {
            bodyBuilder.appendLine("; Global variables")
            for (global in globals) {
                // Use out temporarily
                out.clear()
                emitGlobal(global.stmt)
                bodyBuilder.append(out)
            }
            bodyBuilder.appendLine()
        }

        // Emit functions
        for (item in program.items.filterIsInstance<IrTopLevel.Func>()) {
            out.clear()
            emitFunction(item.function)
            bodyBuilder.append(out)
            bodyBuilder.appendLine()
        }

        // Emit tests
        for (item in program.items.filterIsInstance<IrTopLevel.Test>()) {
            out.clear()
            emitTestFunction(item)
            bodyBuilder.append(out)
            bodyBuilder.appendLine()
        }

        // Emit string constants
        val strConsts = StringBuilder()
        if (stringConstants.isNotEmpty()) {
            strConsts.appendLine("; String constants")
            for ((name, value) in stringConstants) {
                val escaped = escapeForLlvm(value)
                val len = value.length + 1
                strConsts.appendLine("$name = private unnamed_addr constant [$len x i8] c\"$escaped\\00\"")
            }
        }

        // Assemble final output
        out.clear()
        line("; LLVM IR generated by Azora compiler")
        line("target triple = \"x86_64-unknown-linux-gnu\"")
        line("")
        if (usesPuts) line("declare i32 @puts(i8*)")
        if (usesPrintf) line("declare i32 @printf(i8*, ...)")
        if (usesAbort) line("declare void @abort() noreturn")
        if (usesPuts || usesPrintf || usesAbort) line("")
        out.append(bodyBuilder)
        out.append(strConsts)

        return out.toString().trimEnd()
    }

    // -----------------------------------------------------------------------
    // Globals
    // -----------------------------------------------------------------------

    private fun emitGlobal(stmt: IrStmt) {
        when (stmt) {
            is IrStmt.VarDecl -> emitGlobalVar(stmt.name, stmt.type, stmt.initializer)
            is IrStmt.FinDecl -> emitGlobalVar(stmt.name, stmt.type, stmt.initializer)
            is IrStmt.LetDecl -> emitGlobalVar(stmt.name, stmt.type, stmt.initializer)
            else -> line("; unsupported global statement: $stmt")
        }
    }

    private fun emitGlobalVar(name: String, type: IrType, initializer: IrExpr) {
        val llvmType = mapType(type)
        val value = when (initializer) {
            is IrExpr.IntLiteral -> "${initializer.value}"
            is IrExpr.RealLiteral -> {
                val bits = initializer.value.toBits()
                "0x${bits.toULong().toString(16).uppercase()}"
            }
            is IrExpr.CharLiteral -> "${initializer.value.code}"
            is IrExpr.BoolLiteral -> if (initializer.value) "1" else "0"
            is IrExpr.StringLiteral -> {
                val ref = addStringConstant(initializer.value)
                "getelementptr ([${ref.byteLen} x i8], [${ref.byteLen} x i8]* ${ref.name}, i64 0, i64 0)"
            }
            else -> {
                line("; TODO: non-constant global initializer for $name")
                "zeroinitializer"
            }
        }
        line("@$name = global $llvmType $value")
    }

    // -----------------------------------------------------------------------
    // Functions
    // -----------------------------------------------------------------------

    private fun emitTestFunction(test: IrTopLevel.Test) {
        localVars.clear()
        tmpCounter = 0
        labelCounter = 0

        val safeName = test.name.replace(" ", "_").replace("\"", "")
        line("define void @test_$safeName() {")
        line("entry:")

        for (stmt in test.body) {
            emitStmt(stmt)
        }

        emit("  ret void")
        line("}")
    }

    private fun emitFunction(func: IrFunction) {
        localVars.clear()
        tmpCounter = 0
        labelCounter = 0

        val retType = mapType(func.returnType)
        val params = func.params.joinToString(", ") { (name, type) ->
            "${mapType(type)} %$name"
        }

        line("define $retType @${func.name}($params) {")
        line("entry:")

        // Allocate stack space for parameters so they can be referenced
        for ((name, type) in func.params) {
            val alloca = nextTmp()
            emit("  $alloca = alloca ${mapType(type)}")
            emit("  store ${mapType(type)} %$name, ${mapType(type)}* $alloca")
            localVars[name] = alloca
        }

        for (stmt in func.body) {
            emitStmt(stmt)
        }

        // If function is void and no explicit return, add one
        if (func.returnType == IrType.Unit) {
            emit("  ret void")
        }

        line("}")
    }

    // -----------------------------------------------------------------------
    // Statements
    // -----------------------------------------------------------------------

    private fun emitStmt(stmt: IrStmt) {
        when (stmt) {
            is IrStmt.VarDecl -> {
                val type = mapType(stmt.type)
                val alloca = nextTmp()
                emit("  $alloca = alloca $type")
                val value = emitExpr(stmt.initializer)
                emit("  store $type $value, $type* $alloca")
                localVars[stmt.name] = alloca
            }
            is IrStmt.FinDecl -> {
                // Same as var at LLVM level (immutability is a source-level concern)
                val type = mapType(stmt.type)
                val alloca = nextTmp()
                emit("  $alloca = alloca $type")
                val value = emitExpr(stmt.initializer)
                emit("  store $type $value, $type* $alloca")
                localVars[stmt.name] = alloca
            }
            is IrStmt.LetDecl -> {
                val type = mapType(stmt.type)
                val alloca = nextTmp()
                emit("  $alloca = alloca $type")
                val value = emitExpr(stmt.initializer)
                emit("  store $type $value, $type* $alloca")
                localVars[stmt.name] = alloca
            }
            is IrStmt.Assignment -> {
                val alloca = localVars[stmt.name] ?: error("Undefined variable: ${stmt.name}")
                val value = emitExpr(stmt.value)
                val type = mapType(stmt.value.type)
                emit("  store $type $value, $type* $alloca")
            }
            is IrStmt.Return -> {
                if (stmt.value != null) {
                    val value = emitExpr(stmt.value)
                    val type = mapType(stmt.value.type)
                    emit("  ret $type $value")
                } else {
                    emit("  ret void")
                }
            }
            is IrStmt.ExprStmt -> {
                emitExpr(stmt.expr)
            }
            is IrStmt.Zone -> {
                emit("  ; zone begin")
                for (s in stmt.body) emitStmt(s)
                emit("  ; zone end")
            }
            is IrStmt.If -> emitIf(stmt)
            is IrStmt.Assert -> emitAssert(stmt)
            is IrStmt.Trace -> emitTrace(stmt)
        }
    }

    private fun emitAssert(stmt: IrStmt.Assert) {
        usesAbort = true
        usesPuts = true
        val cond = emitExpr(stmt.condition)
        val failLabel = nextLabel("assert_fail")
        val passLabel = nextLabel("assert_pass")
        emit("  br i1 $cond, label %$passLabel, label %$failLabel")
        line("$failLabel:")
        val msg = emitExpr(stmt.message)
        val unused = nextTmp()
        emit("  $unused = call i32 @puts(i8* $msg)")
        emit("  call void @abort()")
        emit("  unreachable")
        line("$passLabel:")
    }

    private fun emitTrace(stmt: IrStmt.Trace) {
        usesPrintf = true
        val msg = emitExpr(stmt.message)
        val fmtRef = addStringConstant("[TRACE] %s\n")
        val fmtPtr = nextTmp()
        emit("  $fmtPtr = getelementptr [${fmtRef.byteLen} x i8], [${fmtRef.byteLen} x i8]* ${fmtRef.name}, i64 0, i64 0")
        val unused = nextTmp()
        emit("  $unused = call i32 (i8*, ...) @printf(i8* $fmtPtr, i8* $msg)")
    }

    private fun emitIf(stmt: IrStmt.If) {
        val cond = emitExpr(stmt.condition)
        val thenLabel = nextLabel("then")
        val elseLabel = nextLabel("else")
        val mergeLabel = nextLabel("merge")

        if (stmt.elseBranch != null) {
            emit("  br i1 $cond, label %$thenLabel, label %$elseLabel")
        } else {
            emit("  br i1 $cond, label %$thenLabel, label %$mergeLabel")
        }

        // Then branch
        line("$thenLabel:")
        for (s in stmt.thenBranch) emitStmt(s)
        emit("  br label %$mergeLabel")

        // Else branch
        if (stmt.elseBranch != null) {
            line("$elseLabel:")
            for (s in stmt.elseBranch) emitStmt(s)
            emit("  br label %$mergeLabel")
        }

        // Merge
        line("$mergeLabel:")
    }

    // -----------------------------------------------------------------------
    // Expressions
    // -----------------------------------------------------------------------

    /**
     * Emits LLVM IR for an expression and returns the register holding the result.
     */
    private fun emitExpr(expr: IrExpr): String = when (expr) {
        is IrExpr.IntLiteral -> "${expr.value}"
        is IrExpr.CharLiteral -> "${expr.value.code}"
        is IrExpr.RealLiteral -> {
            // LLVM requires hex for exact double representation, but decimal works for constants
            val bits = expr.value.toBits()
            "0x${bits.toULong().toString(16).uppercase()}"
        }
        is IrExpr.BoolLiteral -> if (expr.value) "1" else "0"
        is IrExpr.StringLiteral -> {
            val ref = addStringConstant(expr.value)
            val tmp = nextTmp()
            emit("  $tmp = getelementptr [${ref.byteLen} x i8], [${ref.byteLen} x i8]* ${ref.name}, i64 0, i64 0")
            tmp
        }
        is IrExpr.Var -> {
            val alloca = localVars[expr.name]
            val type = mapType(expr.type)
            val tmp = nextTmp()
            if (alloca != null) {
                emit("  $tmp = load $type, $type* $alloca")
            } else {
                // Fall back to global variable
                emit("  $tmp = load $type, $type* @${expr.name}")
            }
            tmp
        }
        is IrExpr.Unary -> emitUnary(expr)
        is IrExpr.Binary -> emitBinary(expr)
        is IrExpr.Call -> emitCall(expr)
    }

    private fun emitUnary(expr: IrExpr.Unary): String {
        val operand = emitExpr(expr.operand)
        val tmp = nextTmp()
        when (expr.op) {
            IrUnaryOp.NEG -> {
                val llvmType = mapType(expr.type)
                when {
                    expr.type in IrType.Companion.integerTypes -> emit("  $tmp = sub $llvmType 0, $operand")
                    expr.type in IrType.Companion.floatTypes -> emit("  $tmp = fneg $llvmType $operand")
                    else -> error("Cannot negate type: ${expr.type}")
                }
            }
            IrUnaryOp.NOT -> emit("  $tmp = xor i1 $operand, 1")
        }
        return tmp
    }

    private fun emitBinary(expr: IrExpr.Binary): String {
        // String * Int → emit a call to a helper (not native LLVM op)
        // For now, treat string ops as calls to runtime helpers
        if (expr.op == IrBinaryOp.ADD && expr.left.type == IrType.String) {
            return emitStringConcat(expr)
        }
        if (expr.op == IrBinaryOp.MUL &&
            (expr.left.type == IrType.String || expr.right.type == IrType.String)) {
            return emitStringRepeat(expr)
        }

        val left = emitExpr(expr.left)
        val right = emitExpr(expr.right)
        val tmp = nextTmp()

        val leftType = expr.left.type
        val llvmType = mapType(leftType)
        when {
            // Integer operations (all integer types)
            leftType in IrType.Companion.integerTypes || leftType == IrType.Char -> {
                // Use unsigned division/modulo for unsigned types
                val isUnsigned = leftType == IrType.UInt || leftType == IrType.UByte || leftType == IrType.UShort || leftType == IrType.ULong || leftType == IrType.UCent
                val inst = when (expr.op) {
                    IrBinaryOp.ADD -> "add $llvmType"
                    IrBinaryOp.SUB -> "sub $llvmType"
                    IrBinaryOp.MUL -> "mul $llvmType"
                    IrBinaryOp.DIV -> if (isUnsigned) "udiv $llvmType" else "sdiv $llvmType"
                    IrBinaryOp.MOD -> if (isUnsigned) "urem $llvmType" else "srem $llvmType"
                    IrBinaryOp.EQ -> "icmp eq $llvmType"
                    IrBinaryOp.NEQ -> "icmp ne $llvmType"
                    IrBinaryOp.LT -> if (isUnsigned) "icmp ult $llvmType" else "icmp slt $llvmType"
                    IrBinaryOp.LTE -> if (isUnsigned) "icmp ule $llvmType" else "icmp sle $llvmType"
                    IrBinaryOp.GT -> if (isUnsigned) "icmp ugt $llvmType" else "icmp sgt $llvmType"
                    IrBinaryOp.GTE -> if (isUnsigned) "icmp uge $llvmType" else "icmp sge $llvmType"
                    else -> error("Unsupported int op: ${expr.op}")
                }
                emit("  $tmp = $inst $left, $right")
            }
            // Float operations (all floating-point types)
            leftType in IrType.Companion.floatTypes -> {
                val inst = when (expr.op) {
                    IrBinaryOp.ADD -> "fadd $llvmType"
                    IrBinaryOp.SUB -> "fsub $llvmType"
                    IrBinaryOp.MUL -> "fmul $llvmType"
                    IrBinaryOp.DIV -> "fdiv $llvmType"
                    IrBinaryOp.EQ -> "fcmp oeq $llvmType"
                    IrBinaryOp.NEQ -> "fcmp one $llvmType"
                    IrBinaryOp.LT -> "fcmp olt $llvmType"
                    IrBinaryOp.LTE -> "fcmp ole $llvmType"
                    IrBinaryOp.GT -> "fcmp ogt $llvmType"
                    IrBinaryOp.GTE -> "fcmp oge $llvmType"
                    else -> error("Unsupported float op: ${expr.op}")
                }
                emit("  $tmp = $inst $left, $right")
            }
            // Boolean operations
            leftType == IrType.Bool -> {
                when (expr.op) {
                    IrBinaryOp.AND -> emit("  $tmp = and i1 $left, $right")
                    IrBinaryOp.OR -> emit("  $tmp = or i1 $left, $right")
                    IrBinaryOp.EQ -> emit("  $tmp = icmp eq i1 $left, $right")
                    IrBinaryOp.NEQ -> emit("  $tmp = icmp ne i1 $left, $right")
                    else -> error("Unsupported bool op: ${expr.op}")
                }
            }
            else -> error("Unsupported binary operand type: ${expr.left.type}")
        }
        return tmp
    }

    private fun emitStringConcat(expr: IrExpr.Binary): String {
        // For string concat, we'd need a runtime helper.
        // Emit a comment and placeholder — real implementation needs malloc + strcpy + strcat.
        val left = emitExpr(expr.left)
        val right = emitExpr(expr.right)
        val tmp = nextTmp()
        emit("  ; TODO: string concatenation runtime call")
        emit("  $tmp = call i8* @__azora_str_concat(i8* $left, i8* $right)")
        return tmp
    }

    private fun emitStringRepeat(expr: IrExpr.Binary): String {
        val (strExpr, intExpr) = if (expr.left.type == IrType.String)
            expr.left to expr.right else expr.right to expr.left
        val str = emitExpr(strExpr)
        val count = emitExpr(intExpr)
        val tmp = nextTmp()
        emit("  ; TODO: string repeat runtime call")
        emit("  $tmp = call i8* @__azora_str_repeat(i8* $str, i32 $count)")
        return tmp
    }

    private fun emitCall(expr: IrExpr.Call): String {
        // Special handling for println
        if (expr.name == "println") {
            return emitPrintln(expr)
        }

        val args = expr.args.map { arg ->
            val value = emitExpr(arg)
            "${mapType(arg.type)} $value"
        }
        val retType = mapType(expr.type)

        return if (expr.type == IrType.Unit) {
            emit("  call void @${expr.name}(${args.joinToString(", ")})")
            "void"
        } else {
            val tmp = nextTmp()
            emit("  $tmp = call $retType @${expr.name}(${args.joinToString(", ")})")
            tmp
        }
    }

    private fun emitPrintln(expr: IrExpr.Call): String {
        if (expr.args.isEmpty()) {
            usesPuts = true
            val nl = addStringConstant("")
            val ptr = nextTmp()
            emit("  $ptr = getelementptr [${nl.byteLen} x i8], [${nl.byteLen} x i8]* ${nl.name}, i64 0, i64 0")
            val unused = nextTmp()
            emit("  $unused = call i32 @puts(i8* $ptr)")
            return "void"
        }

        val arg = expr.args[0]
        val value = emitExpr(arg)

        when (arg.type) {
            IrType.String -> {
                usesPuts = true
                val unused = nextTmp()
                emit("  $unused = call i32 @puts(i8* $value)")
            }
            IrType.Int, IrType.UInt, IrType.Byte, IrType.UByte, IrType.Short, IrType.UShort -> {
                usesPrintf = true
                val fmt = addStringConstant("%d\n")
                val ptr = nextTmp()
                emit("  $ptr = getelementptr [${fmt.byteLen} x i8], [${fmt.byteLen} x i8]* ${fmt.name}, i64 0, i64 0")
                val unused = nextTmp()
                emit("  $unused = call i32 (i8*, ...) @printf(i8* $ptr, ${mapType(arg.type)} $value)")
            }
            IrType.Long, IrType.ULong -> {
                usesPrintf = true
                val fmt = addStringConstant("%lld\n")
                val ptr = nextTmp()
                emit("  $ptr = getelementptr [${fmt.byteLen} x i8], [${fmt.byteLen} x i8]* ${fmt.name}, i64 0, i64 0")
                val unused = nextTmp()
                emit("  $unused = call i32 (i8*, ...) @printf(i8* $ptr, i64 $value)")
            }
            IrType.Cent, IrType.UCent -> {
                usesPrintf = true
                val fmt = addStringConstant("%lld\n")
                val ptr = nextTmp()
                emit("  $ptr = getelementptr [${fmt.byteLen} x i8], [${fmt.byteLen} x i8]* ${fmt.name}, i64 0, i64 0")
                val unused = nextTmp()
                emit("  $unused = call i32 (i8*, ...) @printf(i8* $ptr, i128 $value)")
            }
            IrType.Real, IrType.Float, IrType.Decimal -> {
                usesPrintf = true
                val fmt = addStringConstant("%f\n")
                val ptr = nextTmp()
                emit("  $ptr = getelementptr [${fmt.byteLen} x i8], [${fmt.byteLen} x i8]* ${fmt.name}, i64 0, i64 0")
                val unused = nextTmp()
                emit("  $unused = call i32 (i8*, ...) @printf(i8* $ptr, ${mapType(arg.type)} $value)")
            }
            IrType.Char -> {
                usesPrintf = true
                val fmt = addStringConstant("%c\n")
                val ptr = nextTmp()
                emit("  $ptr = getelementptr [${fmt.byteLen} x i8], [${fmt.byteLen} x i8]* ${fmt.name}, i64 0, i64 0")
                val unused = nextTmp()
                emit("  $unused = call i32 (i8*, ...) @printf(i8* $ptr, i8 $value)")
            }
            IrType.Bool -> {
                usesPuts = true
                val trueRef = addStringConstant("true")
                val falseRef = addStringConstant("false")
                val truePtr = nextTmp()
                val falsePtr = nextTmp()
                val selected = nextTmp()
                emit("  $truePtr = getelementptr [${trueRef.byteLen} x i8], [${trueRef.byteLen} x i8]* ${trueRef.name}, i64 0, i64 0")
                emit("  $falsePtr = getelementptr [${falseRef.byteLen} x i8], [${falseRef.byteLen} x i8]* ${falseRef.name}, i64 0, i64 0")
                emit("  $selected = select i1 $value, i8* $truePtr, i8* $falsePtr")
                val unused = nextTmp()
                emit("  $unused = call i32 @puts(i8* $selected)")
            }
            IrType.Unit -> {
                usesPuts = true
                val nl = addStringConstant("")
                val ptr = nextTmp()
                emit("  $ptr = getelementptr [${nl.byteLen} x i8], [${nl.byteLen} x i8]* ${nl.name}, i64 0, i64 0")
                val unused = nextTmp()
                emit("  $unused = call i32 @puts(i8* $ptr)")
            }
        }
        return "void"
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private fun mapType(type: IrType): String = when (type) {
        IrType.Int -> "i32"
        IrType.UInt -> "i32"
        IrType.Real -> "double"
        IrType.Bool -> "i1"
        IrType.String -> "i8*"
        IrType.Unit -> "void"
        IrType.Char -> "i8"
        IrType.Byte -> "i8"
        IrType.UByte -> "i8"
        IrType.Short -> "i16"
        IrType.UShort -> "i16"
        IrType.Long -> "i64"
        IrType.ULong -> "i64"
        IrType.Cent -> "i128"
        IrType.UCent -> "i128"
        IrType.Float -> "float"
        IrType.Decimal -> "fp128"
    }

    private fun nextTmp(): String = "%${tmpCounter++}"

    private fun nextLabel(prefix: String): String = "${prefix}.${labelCounter++}"

    data class StringRef(val name: String, val byteLen: Int)

    private fun addStringConstant(value: String): StringRef {
        // Check if we already have this string
        for ((name, v) in stringConstants) {
            if (v == value) return StringRef(name, value.length + 1)
        }
        val name = "@.str.$stringCounter"
        stringCounter++
        stringConstants.add(name to value)
        return StringRef(name, value.length + 1)
    }

    private fun escapeForLlvm(s: String): String {
        val sb = StringBuilder()
        for (c in s) {
            when (c) {
                '\\' -> sb.append("\\5C")
                '"' -> sb.append("\\22")
                '\n' -> sb.append("\\0A")
                '\t' -> sb.append("\\09")
                '\r' -> sb.append("\\0D")
                else -> if (c.code in 32..126) sb.append(c)
                        else sb.append("\\${c.code.toString(16).uppercase().padStart(2, '0')}")
            }
        }
        return sb.toString()
    }

    private fun emit(text: String) {
        out.appendLine(text)
    }

    private fun line(text: String) {
        out.appendLine(text)
    }
}
