/*
 * Copyright 2026 AzoraTech
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.azora.lang.backend

import org.azora.lang.ir.IrBinaryOp
import org.azora.lang.ir.IrExpr
import org.azora.lang.ir.IrFunction
import org.azora.lang.ir.IrProgram
import org.azora.lang.ir.IrStmt
import org.azora.lang.ir.IrTopLevel
import org.azora.lang.ir.IrType
import org.azora.lang.ir.IrUnaryOp

/**
 * Backend — lowers [IrProgram] to Swift 6.3 source code.
 *
 * Type mapping:
 *   Int    → Int          Real    → Double        String → String
 *   Bool   → Bool         Unit    → Void          Char   → Character
 *   Byte   → Int8         UByte   → UInt8          Short  → Int16
 *   Long   → Int64        Cent    → Int128         Float  → Float
 *   [T]    → [T]          ![T]    → Set<T>         [K:V]  → [K: V]
 *
 * The generated file is a Swift *script* (`main.swift`): top-level statements are
 * allowed, so an entry-point call (`main()`, or `await main()` for a `task main`)
 * is appended after all declarations when a `main` function is present.
 *
 * `println` maps to `print`, `fin`/`let` map to `let`, `var` maps to `var`.
 *
 * NOTE: Azora packs are reference types, so they lower to Swift `final class`
 * (mutation through a `let` binding stays legal). Collections lower to Swift's
 * value-type `Array`/`Set`/`Dictionary`; a `let`/`fin` binding of a collection
 * therefore emits `var` so element mutation stays legal. Cross-alias mutation of
 * a collection is not observable through a copy (a documented value-semantics
 * limitation, analogous to the other backends' aggregate caveats).
 */
class SwiftCodegen {

    private val out = StringBuilder()
    private var indent = 0
    private var usesPointers = false
    private var usesTasks = false
    private var usesError = false

    private val POINTER_RUNTIME = setOf("__alloc", "__deref", "__derefAssign", "__isolated")

    private val pointerPreamble: String = """
        final class AzoraPtr<T> { var value: T; init(_ v: T) { value = v } }
        func __alloc<T>(_ v: T) -> AzoraPtr<T> { AzoraPtr(v) }
        func __deref<T>(_ p: AzoraPtr<T>) -> T { p.value }
        func __derefAssign<T>(_ p: AzoraPtr<T>, _ v: T) { p.value = v }
        // NOTE: __isolated is a shallow copy in the Swift backend.
        func __isolated<T>(_ v: T) -> T { v }
    """.trimIndent()

    // Structured-concurrency runtime. Everything is pinned to the main actor so it
    // satisfies Swift 6 strict concurrency (top-level `main.swift` code is already
    // main-actor-isolated) and gives deterministic, single-threaded task ordering.
    private val taskPreamble: String = """
        enum __AzoraRuntime {
            @MainActor static var children: [@MainActor () async -> Void] = []
        }
        @MainActor @discardableResult
        func __azoraSpawn<T>(_ body: @escaping @MainActor () async -> T) -> Task<T, Never> {
            let t = Task { @MainActor in await body() }
            __AzoraRuntime.children.append { @MainActor in _ = await t.value }
            return t
        }
        @MainActor
        func __azoraDrainChildren() async {
            while !__AzoraRuntime.children.isEmpty {
                let c = __AzoraRuntime.children.removeFirst()
                await c()
            }
        }
    """.trimIndent()

    private val errorPreamble: String = "struct AzoraError: Error { let value: String }"

    /**
     * Generates Swift 6.3 source code from the given IR program.
     *
     * If a `main` function is present, an entry-point call is appended.
     *
     * @param program the optimized IR program to lower to Swift
     * @return the generated Swift source code as a string
     */
    fun generate(program: IrProgram): String {
        out.clear()
        indent = 0
        usesPointers = false
        usesTasks = program.functions.any { it.isTask }
        usesError = false

        line("// Swift 6.3 source generated by the Azora compiler")
        if (program.packageName != null) line("// package: ${program.packageName}")
        line("")

        for ((i, item) in program.items.withIndex()) {
            when (item) {
                is IrTopLevel.Global -> emitStmt(item.stmt)
                is IrTopLevel.Func -> {
                    emitFunction(item.function)
                    if (i < program.items.lastIndex) line("")
                }
                is IrTopLevel.Test -> {
                    emitTest(item)
                    if (i < program.items.lastIndex) line("")
                }
                is IrTopLevel.Struct -> {
                    emitStruct(item)
                    if (i < program.items.lastIndex) line("")
                }
                is IrTopLevel.Extern -> {
                    // Swift cannot declare arbitrary FFI signatures inline; emit a marker.
                    val params = item.params.joinToString(", ") { (n, t) -> "$n: ${mapType(t)}" }
                    line("// extern func ${item.name}($params) -> ${mapType(item.returnType)}")
                    if (i < program.items.lastIndex) line("")
                }
            }
        }

        // Entry point (top-level `main.swift` script).
        val main = program.functions.firstOrNull { it.name == "main" }
        if (main != null) {
            line("")
            when {
                main.isTask -> {
                    line("await main()")
                    line("await __azoraDrainChildren()")
                }
                main.returnType != IrType.Unit -> line("_ = main()")
                else -> line("main()")
            }
        }

        val preambles = buildList {
            if (usesPointers) add(pointerPreamble)
            if (usesError) add(errorPreamble)
            if (usesTasks) add(taskPreamble)
        }
        val body = out.toString().trimEnd()
        return if (preambles.isEmpty()) body
        else preambles.joinToString("\n\n") + "\n\n" + body
    }

    private fun emitTest(test: IrTopLevel.Test) {
        val safeName = test.name.replace(" ", "_").replace("\"", "")
        line("func __test_$safeName() {")
        indent++
        for (stmt in test.body) emitStmt(stmt)
        indent--
        line("}")
    }

    private fun emitStruct(struct: IrTopLevel.Struct) {
        line("final class ${struct.name} {")
        indent++
        for (f in struct.fields) {
            val kw = if (f.mutable) "var" else "let"
            line("$kw ${f.name}: ${mapType(f.type)}")
        }
        val params = struct.fields.joinToString(", ") { "_ ${it.name}: ${mapType(it.type)}" }
        line("init($params) {")
        indent++
        for (f in struct.fields) line("self.${f.name} = ${f.name}")
        indent--
        line("}")
        indent--
        line("}")
    }

    private fun emitFunction(func: IrFunction) {
        val params = func.params.joinToString(", ") { (name, type) ->
            "_ $name: ${mapType(type)}"
        }
        val async = if (func.isTask) " async" else ""
        val ret = if (func.returnType == IrType.Unit) "" else " -> ${mapType(func.returnType)}"
        // Task functions run on the main actor to interoperate with the (main-actor)
        // structured-concurrency runtime under Swift 6 strict concurrency.
        if (func.isTask) line("@MainActor")
        line("func ${func.name}($params)$async$ret {")
        indent++
        for (stmt in func.body) emitStmt(stmt)
        indent--
        line("}")
    }

    private fun emitStmt(stmt: IrStmt) {
        when (stmt) {
            is IrStmt.VarDecl -> line("var ${stmt.name}: ${mapType(stmt.type)} = ${emitExpr(stmt.initializer)}")
            is IrStmt.FinDecl -> line("${bindKeyword(stmt.type)} ${stmt.name}: ${mapType(stmt.type)} = ${emitExpr(stmt.initializer)}")
            is IrStmt.LetDecl -> line("${bindKeyword(stmt.type)} ${stmt.name}: ${mapType(stmt.type)} = ${emitExpr(stmt.initializer)}")
            is IrStmt.Assignment -> line("${stmt.name} = ${emitExpr(stmt.value)}")
            is IrStmt.IndexAssign -> line("${emitExpr(stmt.target)}[${emitExpr(stmt.index)}] = ${emitExpr(stmt.value)}")
            is IrStmt.MemberAssign -> line("${emitExpr(stmt.target)}.${stmt.name} = ${emitExpr(stmt.value)}")
            is IrStmt.When -> {
                line("switch ${emitExpr(stmt.scrutinee)} {")
                for (b in stmt.branches) {
                    val pats = b.patterns.joinToString(", ") { emitExpr(it) }
                    line("case $pats:")
                    indent++
                    for (s in b.body) emitStmt(s)
                    if (b.body.isEmpty()) line("break")
                    indent--
                }
                if (stmt.elseBranch != null) {
                    line("default:")
                    indent++
                    for (s in stmt.elseBranch) emitStmt(s)
                    if (stmt.elseBranch.isEmpty()) line("break")
                    indent--
                } else {
                    line("default: break")
                }
                line("}")
            }
            is IrStmt.Return -> {
                if (stmt.value != null) line("return ${emitExpr(stmt.value)}")
                else line("return")
            }
            is IrStmt.ExprStmt -> line(emitExpr(stmt.expr))
            is IrStmt.Zone -> {
                line("do {")
                indent++
                for (s in stmt.body) emitStmt(s)
                indent--
                line("}")
            }
            is IrStmt.Assert -> line("precondition(${emitExpr(stmt.condition)}, ${emitExpr(stmt.message)})")
            is IrStmt.Trace -> line("print(\"[TRACE] \\(${emitExpr(stmt.message)})\")")
            is IrStmt.If -> {
                line("if ${emitExpr(stmt.condition)} {")
                indent++
                for (s in stmt.thenBranch) emitStmt(s)
                indent--
                if (stmt.elseBranch != null) {
                    // Collapse a lone nested `if` into an `else if` chain.
                    if (stmt.elseBranch.size == 1 && stmt.elseBranch[0] is IrStmt.If) {
                        val elseIf = stmt.elseBranch[0] as IrStmt.If
                        line("} else if ${emitExpr(elseIf.condition)} {")
                        indent++
                        for (s in elseIf.thenBranch) emitStmt(s)
                        indent--
                        if (elseIf.elseBranch != null) {
                            line("} else {")
                            indent++
                            for (s in elseIf.elseBranch) emitStmt(s)
                            indent--
                        }
                        line("}")
                    } else {
                        line("} else {")
                        indent++
                        for (s in stmt.elseBranch) emitStmt(s)
                        indent--
                        line("}")
                    }
                } else {
                    line("}")
                }
            }
            is IrStmt.While -> {
                val lbl = if (stmt.label != null) "${stmt.label}: " else ""
                line("${lbl}while ${emitExpr(stmt.condition)} {")
                indent++
                for (s in stmt.body) emitStmt(s)
                indent--
                line("}")
            }
            is IrStmt.For -> {
                val lbl = if (stmt.label != null) "${stmt.label}: " else ""
                val step = stmt.step?.let { emitExpr(it) }
                val start = emitExpr(stmt.start)
                val end = emitExpr(stmt.end)
                val seq = when {
                    stmt.reverse -> "stride(from: $end, through: $start, by: -(${step ?: "1"}))"
                    step != null && stmt.inclusive -> "stride(from: $start, through: $end, by: $step)"
                    step != null -> "stride(from: $start, to: $end, by: $step)"
                    stmt.inclusive -> "$start...$end"
                    else -> "$start..<$end"
                }
                line("${lbl}for ${stmt.counter} in $seq {")
                indent++
                for (s in stmt.body) emitStmt(s)
                indent--
                line("}")
            }
            is IrStmt.ForEach -> {
                line("for ${stmt.elem} in ${emitExpr(stmt.iterable)} {")
                indent++
                for (s in stmt.body) emitStmt(s)
                indent--
                line("}")
            }
            is IrStmt.Loop -> {
                val lbl = if (stmt.label != null) "${stmt.label}: " else ""
                line("${lbl}while true {")
                indent++
                for (s in stmt.body) emitStmt(s)
                indent--
                line("}")
            }
            is IrStmt.Throw -> {
                usesError = true
                line("throw AzoraError(value: \"\\(${emitExpr(stmt.value)})\")")
            }
            is IrStmt.Try -> {
                usesError = true
                line("do {")
                indent++
                for (s in stmt.body) emitStmt(s)
                indent--
                if (stmt.catchBody != null) {
                    line("} catch let __azerr {")
                    indent++
                    if (stmt.catchName != null) {
                        line("let ${stmt.catchName} = (__azerr as? AzoraError)?.value ?? \"\\(__azerr)\"")
                    }
                    for (s in stmt.catchBody) emitStmt(s)
                    indent--
                    line("}")
                } else {
                    line("} catch {")
                    line("}")
                }
            }
            is IrStmt.Defer -> {
                // Swift has a native `defer` — run [body] at scope exit.
                line("defer {")
                indent++
                for (s in stmt.body) emitStmt(s)
                indent--
                line("}")
            }
            is IrStmt.Yield -> {}
            is IrStmt.Break -> line(if (stmt.label != null) "break ${stmt.label}" else "break")
            is IrStmt.Continue -> line(if (stmt.label != null) "continue ${stmt.label}" else "continue")
        }
    }

    private fun emitExpr(expr: IrExpr): String = when (expr) {
        is IrExpr.IntLiteral -> when (expr.type) {
            IrType.Int, IrType.Any -> "${expr.value}"
            else -> "${swiftNumericType(expr.type)}(${expr.value})"
        }
        is IrExpr.RealLiteral -> when (expr.type) {
            IrType.Float -> "Float(${expr.value})"
            else -> "${expr.value}"
        }
        is IrExpr.StringLiteral -> "\"${escapeString(expr.value)}\""
        is IrExpr.BoolLiteral -> "${expr.value}"
        is IrExpr.CharLiteral -> "Character(\"${escapeString(expr.value.toString())}\")"
        is IrExpr.Var -> expr.name
        is IrExpr.Unary -> when (expr.op) {
            IrUnaryOp.NEG -> "(-${emitExpr(expr.operand)})"
            IrUnaryOp.NOT -> "(!${emitExpr(expr.operand)})"
            IrUnaryOp.BIT_NOT -> "(~${emitExpr(expr.operand)})"
        }
        is IrExpr.Binary -> {
            val l = expr.left
            val r = expr.right
            when {
                // String * Int → String(repeating:count:)
                expr.op == IrBinaryOp.MUL && l.type == IrType.String && r.type == IrType.Int ->
                    "String(repeating: ${emitExpr(l)}, count: ${emitExpr(r)})"
                expr.op == IrBinaryOp.MUL && l.type == IrType.Int && r.type == IrType.String ->
                    "String(repeating: ${emitExpr(r)}, count: ${emitExpr(l)})"
                // Swift `%` is integer-only; floats use truncatingRemainder.
                expr.op == IrBinaryOp.MOD && expr.type in IrType.floatTypes ->
                    "(${emitExpr(l)}).truncatingRemainder(dividingBy: ${emitExpr(r)})"
                else -> {
                    val op = when (expr.op) {
                        IrBinaryOp.ADD -> "+"
                        IrBinaryOp.SUB -> "-"
                        IrBinaryOp.MUL -> "*"
                        IrBinaryOp.DIV -> "/"
                        IrBinaryOp.MOD -> "%"
                        IrBinaryOp.EQ -> "=="
                        IrBinaryOp.NEQ -> "!="
                        IrBinaryOp.LT -> "<"
                        IrBinaryOp.LTE -> "<="
                        IrBinaryOp.GT -> ">"
                        IrBinaryOp.GTE -> ">="
                        IrBinaryOp.AND -> "&&"
                        IrBinaryOp.OR -> "||"
                        IrBinaryOp.BIT_AND -> "&"; IrBinaryOp.BIT_OR -> "|"; IrBinaryOp.BIT_XOR -> "^"
                        IrBinaryOp.SHL -> "<<"; IrBinaryOp.SHR -> ">>"
                    }
                    "(${emitExpr(l)} $op ${emitExpr(r)})"
                }
            }
        }
        is IrExpr.Call -> {
            if (expr.name in POINTER_RUNTIME) usesPointers = true
            when {
                expr.name == "async" && expr.args.singleOrNull() is IrExpr.Lambda ->
                    "__azoraSpawn(${emitLambda(expr.args.single() as IrExpr.Lambda, async = true)})"
                expr.name == "cancel" && expr.args.size == 1 ->
                    "${emitExpr(expr.args.single())}.cancel()"
                expr.type is IrType.Task ->
                    "__azoraSpawn { await ${expr.name}(${expr.args.joinToString(", ") { emitExpr(it) }}) }"
                else -> {
                    val name = if (expr.name == "println") "print" else expr.name
                    "$name(${expr.args.joinToString(", ") { emitExpr(it) }})"
                }
            }
        }
        is IrExpr.Await -> "(await ${emitExpr(expr.value)}.value)"
        is IrExpr.Spread -> emitExpr(expr.array) // Swift has no splat operator — pass the array
        is IrExpr.ArrayLiteral -> "[${expr.elements.joinToString(", ") { emitExpr(it) }}]"
        is IrExpr.SetLit -> "Set([${expr.elements.joinToString(", ") { emitExpr(it) }}])"
        is IrExpr.MapLit -> {
            if (expr.entries.isEmpty()) "[:]"
            else "[${expr.entries.joinToString(", ") { "${emitExpr(it.first)}: ${emitExpr(it.second)}" }}]"
        }
        is IrExpr.Index -> "${emitExpr(expr.target)}[${emitExpr(expr.index)}]"
        is IrExpr.Member -> when (expr.name) {
            "length" -> "${emitExpr(expr.target)}.count"
            "isEmpty" -> "${emitExpr(expr.target)}.isEmpty"
            "isNotEmpty" -> "(!${emitExpr(expr.target)}.isEmpty)"
            else -> "${emitExpr(expr.target)}.${expr.name}"
        }
        is IrExpr.MethodCall -> when (expr.name) {
            "add" -> "${emitExpr(expr.target)}.append(${expr.args.joinToString(", ") { emitExpr(it) }})"
            "isEmpty" -> "${emitExpr(expr.target)}.isEmpty"
            "isNotEmpty" -> "(!${emitExpr(expr.target)}.isEmpty)"
            else -> "${emitExpr(expr.target)}.${expr.name}(${expr.args.joinToString(", ") { emitExpr(it) }})"
        }
        is IrExpr.StructCtor -> "${expr.name}(${expr.args.joinToString(", ") { emitExpr(it) }})"
        is IrExpr.TupleLit -> "(${expr.elements.joinToString(", ") { emitExpr(it) }})"
        is IrExpr.TupleAccess -> "${emitExpr(expr.target)}.${expr.index}"
        is IrExpr.CatchExpr -> {
            usesError = true
            "{ () -> ${mapType(expr.type)} in do { return ${emitExpr(expr.expr)} } catch { return ${emitExpr(expr.fallback)} } }()"
        }
        is IrExpr.IfExpr -> "(${emitExpr(expr.condition)} ? ${emitExpr(expr.thenExpr)} : ${emitExpr(expr.elseExpr)})"
        is IrExpr.NumCast -> emitNumCast(expr)
        is IrExpr.SlotPattern -> "" /* handled by when lowering */
        is IrExpr.Lambda -> emitLambda(expr, async = false)
        is IrExpr.StringTemplate -> {
            val sb = StringBuilder("\"")
            for (part in expr.parts) {
                when (part) {
                    is IrExpr.IrTemplatePart.Literal -> sb.append(escapeString(part.text))
                    is IrExpr.IrTemplatePart.Expr -> sb.append("\\(").append(emitExpr(part.expr)).append(")")
                }
            }
            sb.append("\"").toString()
        }
    }

    /** Emits a lambda/closure. When [async] the closure is marked `async`. */
    private fun emitLambda(expr: IrExpr.Lambda, async: Boolean): String {
        val retType = (expr.type as? IrType.Function)?.ret ?: IrType.Unit
        val ps = expr.params.joinToString(", ") { (n, t) -> "$n: ${mapType(t)}" }
        val asyncKw = if (async) " async" else ""
        val header = "($ps)$asyncKw -> ${mapType(retType)} in"
        val ret = expr.body.singleOrNull() as? IrStmt.Return
        if (ret != null) {
            val value = if (ret.value != null) "return ${emitExpr(ret.value)}" else "return"
            return "{ $header $value }"
        }
        val body = capture {
            indent++
            for (s in expr.body) emitStmt(s)
            indent--
        }
        val pad = "    ".repeat(indent)
        return "{ $header\n$body$pad}"
    }

    private fun emitNumCast(expr: IrExpr.NumCast): String {
        val src = expr.value.type
        val sourceNumeric = src in IrType.integerTypes || src in IrType.floatTypes || src == IrType.Char
        if (!sourceNumeric) return emitExpr(expr.value) // pointer/FFI cast — pass through
        val v = emitExpr(expr.value)
        // Char target — build from a scalar code point.
        if (expr.type == IrType.Char) {
            return if (src == IrType.Char) v else "Character(UnicodeScalar(Int($v))!)"
        }
        val target = swiftNumericType(expr.type)
        // Char source — read its Unicode scalar value first.
        if (src == IrType.Char) return "$target($v.unicodeScalars.first!.value)"
        return when {
            // Integer → integer conversions wrap (match the other backends' truncation).
            expr.type in IrType.integerTypes && src in IrType.integerTypes -> "$target(truncatingIfNeeded: $v)"
            else -> "$target($v)"
        }
    }

    /** `let` for immutable scalars, but `var` for collections so element mutation stays legal. */
    private fun bindKeyword(type: IrType): String = when (type) {
        is IrType.Array, is IrType.Map, is IrType.Set -> "var"
        else -> "let"
    }

    /** The Swift constructor/type name for a numeric [IrType]. */
    private fun swiftNumericType(type: IrType): String = when (type) {
        IrType.Int -> "Int"
        IrType.UInt -> "UInt"
        IrType.Byte -> "Int8"
        IrType.UByte -> "UInt8"
        IrType.Short -> "Int16"
        IrType.UShort -> "UInt16"
        IrType.Long -> "Int64"
        IrType.ULong -> "UInt64"
        IrType.Cent -> "Int128"
        IrType.UCent -> "UInt128"
        IrType.Float -> "Float"
        IrType.Real, IrType.Decimal -> "Double"
        else -> "Int"
    }

    private fun mapType(type: IrType): String = when (type) {
        IrType.Int -> "Int"
        IrType.UInt -> "UInt"
        IrType.Real -> "Double"
        IrType.String -> "String"
        IrType.Bool -> "Bool"
        IrType.Unit -> "Void"
        IrType.Char -> "Character"
        IrType.Byte -> "Int8"
        IrType.UByte -> "UInt8"
        IrType.Short -> "Int16"
        IrType.UShort -> "UInt16"
        IrType.Long -> "Int64"
        IrType.ULong -> "UInt64"
        IrType.Cent -> "Int128"
        IrType.UCent -> "UInt128"
        IrType.Float -> "Float"
        IrType.Decimal -> "Double" // best available Swift type
        is IrType.Array -> "[${mapType(type.element)}]"
        is IrType.Set -> "Set<${mapType(type.element)}>"
        is IrType.Map -> "[${mapType(type.key)}: ${mapType(type.value)}]"
        is IrType.Pointer -> "AzoraPtr<${mapType(type.inner)}>"
        is IrType.Function -> "(${type.params.joinToString(", ") { mapType(it) }}) -> ${mapType(type.ret)}"
        is IrType.Task -> "Task<${mapType(type.result)}, Never>"
        is IrType.Tuple -> "(${type.elements.joinToString(", ") { mapType(it) }})"
        is IrType.Nullable -> "${mapType(type.inner)}?"
        is IrType.Named -> type.name
        IrType.Any -> "Any"
    }

    /** Emits [block] into a scratch region of [out] and returns (and removes) the produced text. */
    private fun capture(block: () -> Unit): String {
        val start = out.length
        block()
        val text = out.substring(start)
        out.setLength(start)
        return text
    }

    private fun escapeString(s: String): String =
        s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
            .replace("\t", "\\t").replace("\r", "\\r")

    private fun line(text: String) {
        repeat(indent) { out.append("    ") }
        out.appendLine(text)
    }
}
