package org.azora.lang.codegen

import org.azora.lang.CompilationResult
import org.azora.lang.Compiler
import org.azora.lang.ir.IrExpr
import org.azora.lang.ir.IrStmt
import kotlin.test.*

class MetaprogrammingTest {

    private fun compile(source: String): CompilationResult.Success {
        val result = Compiler().compile(source)
        assertIs<CompilationResult.Success>(result, "Compilation failed: ${(result as? CompilationResult.Failure)?.errors}")
        return result
    }

    @Test
    fun inlineFunc_bodySubstitutedAtCallSite() {
        val result = compile("""
            package playground

            inline func a() {
                println("Hello from A")
            }

            func b() {
                println("Hello from B")
            }

            func main() {
                a()
                b()
            }
        """.trimIndent())

        val expectedIr = """
            package playground

            func b(): Unit {
                println("Hello from B")
            }

            func main(): Unit {
                zone {
                    println("Hello from A")
                }
                b()
            }
        """.trimIndent()

        val expectedOptimizedIr = """
            package playground

            func b(): Unit {
                println("Hello from B")
            }

            func main(): Unit {
                zone {
                    println("Hello from A")
                }
                b()
            }
        """.trimIndent()

        val expectedKotlin = """
            package playground

            fun b(): Unit {
                println("Hello from B")
            }

            fun main(): Unit {
                run {
                    println("Hello from A")
                }
                b()
            }
        """.trimIndent()

        val expectedTypeScript = """
            // package: playground

            function b(): void {
                console.log("Hello from B");
            }

            function main(): void {
                {
                    console.log("Hello from A");
                }
                b();
            }

            main()
        """.trimIndent()

        val expectedLlvm = """
            ; LLVM IR generated by Azora compiler
            target triple = "x86_64-unknown-linux-gnu"

            declare i32 @puts(i8*)

            define void @b() {
            entry:
              %0 = getelementptr [13 x i8], [13 x i8]* @.str.0, i64 0, i64 0
              %1 = call i32 @puts(i8* %0)
              ret void
            }

            define void @main() {
            entry:
              ; zone begin
              %0 = getelementptr [13 x i8], [13 x i8]* @.str.1, i64 0, i64 0
              %1 = call i32 @puts(i8* %0)
              ; zone end
              call void @b()
              ret void
            }

            ; String constants
            @.str.0 = private unnamed_addr constant [13 x i8] c"Hello from B\00"
            @.str.1 = private unnamed_addr constant [13 x i8] c"Hello from A\00"
        """.trimIndent()

        assertEquals(expectedIr, result.ir.prettyPrint())
        assertEquals(expectedOptimizedIr, result.optimizedIr.prettyPrint())
        assertEquals(expectedKotlin, result.kotlin)
        assertEquals(expectedTypeScript, result.typescript)
        assertEquals(expectedLlvm, result.llvm)
    }

    @Test
    fun inlineBlocks_funcInliningRules() {
        val result = compile("""
            package playground

            inline fin x = 2

            inline {
                fin a1 = 0

                func a() {
                    println("Hello from A")
                }
            }

            deepinline {
                fin b1 = 0

                func b() {
                    println("Hello from B")
                }
            }

            inline if x == 2 {
                func c() {
                    println("Hello from C")
                }
            }

            deepinline if x == 2 {
                func d() {
                    println("Hello from D")
                }
            }

            deepinline if x == 2 {
                noinline func e() {
                    println("Hello from E")
                }
            }

            func main() {
                a()
                b()
                c()
                d()
                e()
            }
        """.trimIndent())

        // a, b, d are inline — NOT in IR
        // c, e are runtime — IN IR
        val irFuncNames = result.ir.functions.map { it.name }
        assertFalse("a" in irFuncNames, "inline { func a() } should not be in IR")
        assertFalse("b" in irFuncNames, "deepinline { func b() } should not be in IR")
        assertTrue("c" in irFuncNames, "inline if { func c() } should be in IR")
        assertFalse("d" in irFuncNames, "deepinline if { func d() } should not be in IR")
        assertTrue("e" in irFuncNames, "noinline func e() should be in IR")
        assertTrue("main" in irFuncNames, "func main() should be in IR")

        // main() should have a, b, d inlined as zone blocks, and call c, e directly
        val mainBody = result.ir.functions.first { it.name == "main" }.body
        val zones = mainBody.filterIsInstance<IrStmt.Zone>()
        val calls = mainBody.filterIsInstance<IrStmt.ExprStmt>()
            .map { it.expr }.filterIsInstance<IrExpr.Call>().map { it.name }

        assertEquals(3, zones.size, "main should have 3 zone blocks (inlined a, b, d)")
        assertTrue("c" in calls, "main should call c() directly")
        assertTrue("e" in calls, "main should call e() directly")
    }

    @Test
    fun runtimeGlobals_finSurvivesInIr() {
        val result = compile("""
            package playground

            inline fin x = 2

            inline if x == 2 {
                fin c1 = 0

                func c() {
                    println("Hello from C")
                }
            }

            deepinline if x == 2 {
                noinline fin e1 = 0

                noinline func e() {
                    println("Hello from E")
                }
            }

            func main() {
                c()
                e()
            }
        """.trimIndent())

        // c1 and e1 should be in IR globals
        val globalNames = result.ir.globals.map {
            when (it) {
                is IrStmt.FinDecl -> it.name
                else -> ""
            }
        }
        assertTrue("c1" in globalNames, "fin c1 should be a global in IR, got: ${result.ir.globals}")
        assertTrue("e1" in globalNames, "fin e1 should be a global in IR, got: ${result.ir.globals}")

        // Pretty-print should include globals
        val ir = result.ir.prettyPrint()
        assertTrue("fin c1: Int = 0" in ir, "IR should contain 'fin c1: Int = 0', got:\n$ir")
        assertTrue("fin e1: Int = 0" in ir, "IR should contain 'fin e1: Int = 0', got:\n$ir")
    }

    @Test
    fun fullMetaprogramming_allInlineRulesWithGlobals() {
        val result = compile("""
            package playground

            inline fin x = 2

            fin aa = 2

            inline {
                fin a1 = 0

                func a() {
                    println("Hello from A")
                }
            }

            deepinline {
                fin b1 = 0

                func b() {
                    println("Hello from B")
                }
            }

            inline if x == 2 {
                fin c1 = 0

                func c() {
                    println("Hello from C")
                }
            }

            deepinline if x == 2 {
                fin d1 = 0

                func d() {
                    println("Hello from D")
                }
            }

            deepinline if x == 2 {
                noinline fin e1 = 0

                noinline func e() {
                    println("Hello from E")
                }
            }

            func main() {
                a()
                b()
                c()
                d()
                e()
            }
        """.trimIndent())

        val expectedIr = """
            package playground

            fin aa: Int = 2
            fin c1: Int = 0

            func c(): Unit {
                println("Hello from C")
            }

            fin e1: Int = 0

            func e(): Unit {
                println("Hello from E")
            }

            func main(): Unit {
                zone {
                    println("Hello from A")
                }
                zone {
                    println("Hello from B")
                }
                c()
                zone {
                    println("Hello from D")
                }
                e()
            }
        """.trimIndent()

        val expectedKotlin = """
            package playground

            fun c(): Unit {
                println("Hello from C")
            }

            fun e(): Unit {
                println("Hello from E")
            }

            fun main(): Unit {
                run {
                    println("Hello from A")
                }
                run {
                    println("Hello from B")
                }
                c()
                run {
                    println("Hello from D")
                }
                e()
            }
        """.trimIndent()

        val expectedTypeScript = """
            // package: playground

            function c(): void {
                console.log("Hello from C");
            }

            function e(): void {
                console.log("Hello from E");
            }

            function main(): void {
                {
                    console.log("Hello from A");
                }
                {
                    console.log("Hello from B");
                }
                c();
                {
                    console.log("Hello from D");
                }
                e();
            }

            main()
        """.trimIndent()

        val expectedLlvm = """
            ; LLVM IR generated by Azora compiler
            target triple = "x86_64-unknown-linux-gnu"

            declare i32 @puts(i8*)

            define void @c() {
            entry:
              %0 = getelementptr [13 x i8], [13 x i8]* @.str.0, i64 0, i64 0
              %1 = call i32 @puts(i8* %0)
              ret void
            }

            define void @e() {
            entry:
              %0 = getelementptr [13 x i8], [13 x i8]* @.str.1, i64 0, i64 0
              %1 = call i32 @puts(i8* %0)
              ret void
            }

            define void @main() {
            entry:
              ; zone begin
              %0 = getelementptr [13 x i8], [13 x i8]* @.str.2, i64 0, i64 0
              %1 = call i32 @puts(i8* %0)
              ; zone end
              ; zone begin
              %2 = getelementptr [13 x i8], [13 x i8]* @.str.3, i64 0, i64 0
              %3 = call i32 @puts(i8* %2)
              ; zone end
              call void @c()
              ; zone begin
              %4 = getelementptr [13 x i8], [13 x i8]* @.str.4, i64 0, i64 0
              %5 = call i32 @puts(i8* %4)
              ; zone end
              call void @e()
              ret void
            }

            ; String constants
            @.str.0 = private unnamed_addr constant [13 x i8] c"Hello from C\00"
            @.str.1 = private unnamed_addr constant [13 x i8] c"Hello from E\00"
            @.str.2 = private unnamed_addr constant [13 x i8] c"Hello from A\00"
            @.str.3 = private unnamed_addr constant [13 x i8] c"Hello from B\00"
            @.str.4 = private unnamed_addr constant [13 x i8] c"Hello from D\00"
        """.trimIndent()

        val expectedOptimizedIr = """
            package playground

            func c(): Unit {
                println("Hello from C")
            }

            func e(): Unit {
                println("Hello from E")
            }

            func main(): Unit {
                zone {
                    println("Hello from A")
                }
                zone {
                    println("Hello from B")
                }
                c()
                zone {
                    println("Hello from D")
                }
                e()
            }
        """.trimIndent()

        assertEquals(expectedIr, result.ir.prettyPrint())
        assertEquals(expectedOptimizedIr, result.optimizedIr.prettyPrint())
        assertEquals(expectedKotlin, result.kotlin)
        assertEquals(expectedTypeScript, result.typescript)
        assertEquals(expectedLlvm, result.llvm)
    }
}
